DROP TABLE isotopic_pb_samples IF EXISTS;
DROP TABLE concentration_pb_samples IF EXISTS;
DROP TABLE rb_samples IF EXISTS;
DROP TABLE u_samples IF EXISTS;

DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE global_seq AS INTEGER START WITH 100000;

CREATE TABLE isotopic_pb_samples
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  sampleName             VARCHAR(255)               NOT NULL,
  date                   DATE DEFAULT CURRENT_DATE  NOT NULL,
  ratio206204            DOUBLE                     NOT NULL,
  err206204              DOUBLE                     NOT NULL,
  ratio206207            DOUBLE                     NOT NULL,
  err206207              DOUBLE                     NOT NULL,
  ratio206208            DOUBLE                     NOT NULL,
  err206208              DOUBLE                     NOT NULL,
  CONSTRAINT is_pb_unique_idx UNIQUE (sampleName)
);

CREATE TABLE concentration_pb_samples
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  sampleName             VARCHAR(255)               NOT NULL,
  date                   DATE DEFAULT CURRENT_DATE  NOT NULL,
  ratio206204            DOUBLE                     NOT NULL,
  err206204              DOUBLE                     NOT NULL,
  ratio206207            DOUBLE                     NOT NULL,
  err206207              DOUBLE                     NOT NULL,
  ratio206208            DOUBLE                     NOT NULL,
  err206208              DOUBLE                     NOT NULL,
  CONSTRAINT con_pb_unique_idx UNIQUE (sampleName)
);

CREATE TABLE rb_samples
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  sampleName             VARCHAR(255)               NOT NULL,
  date                   DATE DEFAULT CURRENT_DATE  NOT NULL,
  ratio8587              DOUBLE                     NOT NULL,
  err8587                DOUBLE                     NOT NULL,
  CONSTRAINT rb_unique_idx UNIQUE (sampleName)
);

CREATE TABLE u_samples
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  sampleName              VARCHAR(255)               NOT NULL,
  date                    DATE DEFAULT CURRENT_DATE  NOT NULL,
  ratio238235             DOUBLE                     NOT NULL,
  err238235               DOUBLE                     NOT NULL,
  CONSTRAINT u_unique_idx UNIQUE (sampleName)
);